services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn yourprojectname.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: yourprojectname.settings
      - key: PYTHON_VERSION
        value: 3.10
